bug_tracker/urls.py
# https://docs.djangoproject.com/en/3.2/topics/http/urls/

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tracker/', include('tracker.urls')),
    path('', include('home.urls')),
    path('users/', include('users.urls')),

]

handler400 = 'home.views.error_400'
handler403 = 'home.views.error_403'
handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home')
]

tracker/urls.py
from django.urls import path
from tracker.views import tracker, ticket, ticket_comment, general


app_name = 'tracker'
urlpatterns = [
	# GENERAL
	path('dashboard/', general.Dashboard.as_view(), name='dashboard'),
	path('solved/', general.SolvedTicketListView.as_view(), name='solved'),
	path('closed/', general.ClosedTicketListView.as_view(), name='closed'),
	path('pending/', general.PendingTicketListView.as_view(), name='pending'),
	path('open/', general.OpenTicketListView.as_view(), name='open'),

	# TRACKER
	path('list/', tracker.TrackerListView.as_view(), name='tracker-list'),
	path('create/', tracker.TrackerCreateView.as_view(), name='tracker-create'),
	path('<int:pk>/', tracker.TrackerDetailView.as_view(), name='tracker-detail'),
	path('update/<int:pk>/', tracker.TrackerUpdateView.as_view(), name='tracker-update'),
	path('delete/<int:pk>/', tracker.TrackerDeleteView.as_view(), name='tracker-delete'),

	# TICKET
	path('<int:tracker_pk>/ticket/create/', ticket.TicketCreateView.as_view(), name='ticket-create'),
	path('<int:tracker_pk>/ticket/<int:pk>/', ticket.TicketDetailView.as_view(), name='ticket-detail'),
	path('<int:tracker_pk>/ticket/update/<int:pk>/', ticket.TicketUpdateView.as_view(), name='ticket-update'),
	path('<int:tracker_pk>/ticket/delete/<int:pk>/', ticket.TicketDeleteView.as_view(), name='ticket-delete'),

	# TICKET COMMENT
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/create/', ticket_comment.TicketCommentCreateView.as_view(), name='ticket-comment-create'),
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/update/<int:pk>/', ticket_comment.TicketCommentUpdateView.as_view(), name='ticket-comment-update'),
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/delete/<int:pk>/', ticket_comment.TicketCommentDeleteView.as_view(), name='ticket-comment-delete'),

]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
	path('list/', views.UserListView.as_view(), name='list'),
	path('<int:pk>/', views.UserDetailView.as_view(), name='detail'),
	path('update/<int:pk>/', views.UserUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.UserDeleteView.as_view(), name='delete'),
]

tracker/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils.translation import gettext as _


class TimestampMixin(models.Model):
	creator = models.ForeignKey(verbose_name=_("Creator"), to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='%(class)s_creator')
	updater = models.ForeignKey(verbose_name=_("Updater"), to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='%(class)s_updater')
	created_at = models.DateTimeField(verbose_name=_("Date created"), auto_now_add=True)
	updated_at = models.DateTimeField(verbose_name=_("Date updated"), auto_now=True)

	class Meta:
		abstract = True
		# ordering = ['updated_at']
		verbose_name = _("TimestampMixin")
		verbose_name_plural = _("TimestampMixins")


class Tracker(TimestampMixin):
	title = models.CharField(verbose_name=_("Title"), default='', max_length=20)
	description = models.TextField(verbose_name=_("Description"), default='', max_length=500)

	@staticmethod
	def get_list_url():
		return reverse('tracker:tracker-list')

	@staticmethod
	def get_create_url():
		return reverse('tracker:tracker-create')

	def get_absolute_url(self):
		return reverse('tracker:tracker-detail', kwargs={'pk': self.pk})

	def get_update_url(self):
		return reverse('tracker:tracker-update', kwargs={'pk': self.pk})

	def get_delete_url(self):
		return reverse('tracker:tracker-delete', kwargs={'pk': self.pk})

	def __str__(self):
		return self.title

	class Meta:
		# ordering = ['title']
		verbose_name = _("Tracker")
		verbose_name_plural = _("Trackers")


class Ticket(TimestampMixin):
	# TYPE CHOICES
	FEATURE = 'FEATURE'
	BUG = 'BUG'
	UI = 'UI'
	TYPE_CHOICES = [
		(BUG, 'Bug'),
		(UI, 'User-Interface'),
		(FEATURE, 'Feature'),
	]  # (stored, displayed)

	# status CHOICES
	OPEN = 'OPEN'
	CLOSED = 'CLOSED'
	IN_PROGRESS = 'IN PROGRESS'
	RESOLVED = 'RESOLVED'
	STATUS_CHOICES = [
		(OPEN, 'Open'),
		(CLOSED, 'Closed'),
		(IN_PROGRESS, 'In progress'),
		(RESOLVED, 'Resolved'),
	]

	# PRIORITY CHOICES
	CRITICAL = 'CRITICAL'
	HIGH = 'HIGH'
	NORMAL = 'NORMAL'
	LOW = 'LOW'
	PRIORITY_CHOICES = [
		(CRITICAL, 'Critical'),
		(HIGH, 'High'),
		(NORMAL, 'Normal'),
		(LOW, 'Low'),
	]
	title = models.CharField(verbose_name=_("Title"), default='', max_length=20)
	description = models.TextField(verbose_name=_("Description"), default='', max_length=500)
	type = models.CharField(verbose_name=_("Type"), default=BUG, max_length=11, choices=TYPE_CHOICES)
	status = models.CharField(verbose_name=_("Status"), default=OPEN, max_length=11, choices=STATUS_CHOICES)
	priority = models.CharField(verbose_name=_("Priority"), default=NORMAL, max_length=8, choices=PRIORITY_CHOICES)
	assignees = models.ManyToManyField(verbose_name=_("Assignees"), blank=True, to=settings.AUTH_USER_MODEL, related_name='assignees')
	tracker = models.ForeignKey(verbose_name=_("Tracker"), to=Tracker, on_delete=models.CASCADE)
	votes = models.IntegerField(verbose_name=_("Votes"), default=0)
	vote_profiles = models.ManyToManyField(verbose_name=_("Vote profiles"), blank=True, to=settings.AUTH_USER_MODEL, related_name='vote_profiles')
	# todo add attachment file field

	@staticmethod
	def get_list_url():
		return reverse('tracker:ticket-list')

	def get_absolute_url(self):
		return reverse('tracker:ticket-detail', kwargs={'tracker_pk': self.tracker.pk, 'pk': self.pk})

	def get_update_url(self):
		return reverse('tracker:ticket-update', kwargs={'tracker_pk': self.tracker.pk, 'pk': self.pk})

	def get_delete_url(self):
		return reverse('tracker:ticket-delete', kwargs={'tracker_pk': self.tracker.pk, 'pk': self.pk})

	def __str__(self):
		return self.title

	class Meta:
		# ordering = ['title']
		verbose_name = _("Ticket")
		verbose_name_plural = _("Tickets")


class TicketComment(TimestampMixin):
	title = models.CharField(verbose_name=_("Title"), default='', max_length=20)
	comment = models.TextField(verbose_name=_("Comment"), default='', max_length=500)
	ticket = models.ForeignKey(verbose_name=_("Ticket"), to=Ticket, on_delete=models.CASCADE)

	@staticmethod
	def get_list_url():
		return reverse('tracker:ticket-comment-list')

	@staticmethod
	def get_create_url():
		return reverse('tracker:ticket-comment-create')

	def get_absolute_url(self):  # redirect to ticket
		return reverse('tracker:ticket-detail', kwargs={'tracker_pk': self.ticket.tracker.pk, 'pk': self.ticket.pk})

	def get_update_url(self):
		return reverse('tracker:ticket-comment-update', kwargs={{'tracker_pk': self.ticket.tracker.pk, 'ticket_pk': self.ticket.pk, 'pk': self.pk}})

	def get_delete_url(self):
		return reverse('tracker:ticket-comment-delete', kwargs={{'tracker_pk': self.ticket.tracker.pk, 'ticket_pk': self.ticket.pk, 'pk': self.pk}})

	def __str__(self):
		return self.title

	class Meta:
		# ordering = ['title']
		verbose_name = _("Ticket comment")
		verbose_name_plural = _("Ticket comments")

tracker/views/general.py
from django.views.generic import TemplateView, ListView
from bug_tracker.constants import ALL_GROUPS, PAG_BY
from tracker.mixins import GroupsRequiredMixin
from tracker.models import Ticket


class Dashboard(GroupsRequiredMixin, TemplateView):
	template_name = 'tracker/general/dashboard.html'
	groups = ALL_GROUPS

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['tickets'] = Ticket.objects.order_by('-votes')[:10]
		return context


class SolvedTicketListView(GroupsRequiredMixin, ListView):
	model = Ticket
	template_name = 'tracker/general/dashboard_tickets/solved.html'
	groups = ALL_GROUPS
	paginate_by = PAG_BY
	queryset = Ticket.objects.filter(status=Ticket.RESOLVED)


class ClosedTicketListView(GroupsRequiredMixin, ListView):
	model = Ticket
	template_name = 'tracker/general/dashboard_tickets/closed.html'
	groups = ALL_GROUPS
	paginate_by = PAG_BY
	queryset = Ticket.objects.filter(status=Ticket.CLOSED)


class PendingTicketListView(GroupsRequiredMixin, ListView):
	model = Ticket
	template_name = 'tracker/general/dashboard_tickets/pending.html'
	groups = ALL_GROUPS
	paginate_by = PAG_BY
	queryset = Ticket.objects.filter(status=Ticket.IN_PROGRESS)


class OpenTicketListView(GroupsRequiredMixin, ListView):
	model = Ticket
	template_name = 'tracker/general/dashboard_tickets/open.html'
	groups = ALL_GROUPS
	paginate_by = PAG_BY
	queryset = Ticket.objects.filter(status=Ticket.OPEN)

tracker/views/ticket.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from bug_tracker.constants import ALL_GROUPS, ADMINS, NOT_VIEWER, PAG_BY
from tracker.models import Tracker, Ticket
from tracker.model_forms import TicketModelForm
from tracker.mixins import GroupsRequiredMixin


class TicketCreateView(GroupsRequiredMixin, CreateView):
	model = Ticket
	form_class = TicketModelForm
	template_name = 'tracker/models/ticket/create.html'
	groups = NOT_VIEWER

	def form_valid(self, form):
		form.instance.creator = self.request.user
		form.instance.updater = self.request.user
		form.instance.tracker = Tracker.objects.get(pk=self.kwargs['tracker_pk'])
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()


class TicketDetailView(GroupsRequiredMixin, DetailView):
	model = Ticket
	template_name = 'tracker/models/ticket/detail.html'
	groups = ALL_GROUPS


class TicketUpdateView(UserPassesTestMixin, UpdateView):
	model = Ticket
	form_class = TicketModelForm
	template_name = 'tracker/models/ticket/update.html'

	def form_valid(self, form):
		form.instance.updater = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()

	def test_func(self):
		is_creator = self.get_object().creator == self.request.user
		is_admin = self.request.user.groups.filter(name__in=ADMINS).exists()
		return is_creator or is_admin


class TicketDeleteView(UserPassesTestMixin, DeleteView):
	model = Ticket
	template_name = 'tracker/models/ticket/delete.html'

	def get_success_url(self):
		return Tracker.get_list_url()

	def test_func(self):
		is_creator = self.get_object().creator == self.request.user
		is_admin = self.request.user.groups.filter(name__in=ADMINS).exists()
		return is_creator or is_admin

tracker/views/ticket_comment.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import reverse
from bug_tracker.constants import ADMINS, NOT_VIEWER
from tracker.models import Ticket, TicketComment
from tracker.model_forms import TicketCommentModelForm
from tracker.mixins import GroupsRequiredMixin


class TicketCommentCreateView(GroupsRequiredMixin, CreateView):
	model = TicketComment
	form_class = TicketCommentModelForm
	template_name = 'tracker/models/ticket_comment/create.html'
	groups = NOT_VIEWER

	def form_valid(self, form):
		form.instance.creator = self.request.user
		form.instance.updater = self.request.user
		form.instance.ticket = Ticket.objects.get(pk=self.kwargs['ticket_pk'])
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()


class TicketCommentUpdateView(UserPassesTestMixin, UpdateView):
	model = TicketComment
	form_class = TicketCommentModelForm
	template_name = 'tracker/models/ticket_comment/update.html'

	def form_valid(self, form):
		form.instance.updater = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()

	def test_func(self):
		is_creator = self.get_object().creator == self.request.user
		is_admin = self.request.user.groups.filter(name__in=ADMINS).exists()
		return is_creator or is_admin


class TicketCommentDeleteView(UserPassesTestMixin, DeleteView):
	model = TicketComment
	template_name = 'tracker/models/ticket_comment/delete.html'

	def get_success_url(self):
		return reverse('tracker:ticket-detail', kwargs={'tracker_pk': self.object.ticket.tracker.pk, 'pk': self.object.ticket.pk})

	def test_func(self):
		is_creator = self.get_object().creator == self.request.user
		is_admin = self.request.user.groups.filter(name__in=ADMINS).exists()
		return is_creator or is_admin

tracker/views/tracker.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from bug_tracker.constants import ADMINS, ALL_GROUPS, PAG_BY
from tracker.models import Tracker
from tracker.model_forms import TrackerModelForm
from tracker.mixins import GroupsRequiredMixin


class TrackerListView(GroupsRequiredMixin, ListView):
	model = Tracker
	template_name = 'tracker/models/tracker/list.html'
	groups = ALL_GROUPS
	paginate_by = PAG_BY
	extra_context = {
		'model': Tracker,
	}


class TrackerCreateView(GroupsRequiredMixin, CreateView):
	model = Tracker
	form_class = TrackerModelForm
	template_name = 'tracker/models/tracker/create.html'
	groups = ADMINS

	def form_valid(self, form):
		form.instance.creator = self.request.user
		form.instance.updater = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()


class TrackerDetailView(GroupsRequiredMixin, DetailView):
	model = Tracker
	template_name = 'tracker/models/tracker/detail.html'
	groups = ALL_GROUPS


class TrackerUpdateView(GroupsRequiredMixin, UpdateView):
	model = Tracker
	form_class = TrackerModelForm
	template_name = 'tracker/models/tracker/update.html'
	groups = ADMINS

	def form_valid(self, form):
		form.instance.updater = self.request.user
		return super().form_valid(form)

	def get_success_url(self):
		return self.object.get_absolute_url()


class TrackerDeleteView(GroupsRequiredMixin, DeleteView):
	model = Tracker
	template_name = 'tracker/models/tracker/delete.html'
	groups = ADMINS

	def get_success_url(self):
		return self.model.get_list_url()

tracker/templates/tracker/general/includes/breadcrumbs.html
<h1 class="mt-4">Dashboard</h1>
<ol class="breadcrumb">
    <li class="breadcrumb-item active"><a href="{% url 'home:home' %}">Home</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'tracker:tracker-list' %}">Bug Trackers</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'users:detail' user.pk %}">Profile</a></li>
    <li class="breadcrumb-item active"><a href="{% url 'users:list' %}">Users</a></li>
</ol>

tracker/templates/tracker/general/includes/cards.html
<div class="row">
    <div class="col-xl-3 col-md-6">
        <a href="{% url 'tracker:solved' %}" class="text-decoration-none">
            <div class="card bg-primary text-light text-center mb-4 p-3">
                <div class="card-body">
                    <h3>Solved Tickets</h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-xl-3 col-md-6">
        <a href="{% url 'tracker:closed' %}" class="text-decoration-none">
            <div class="card bg-success text-light text-center mb-4 p-3">
                <div class="card-body">
                    <h3>Closed Tickets</h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-xl-3 col-md-6">
        <a href="{% url 'tracker:pending' %}" class="text-decoration-none">
            <div class="card bg-warning text-light text-center mb-4 p-3">
                <div class="card-body">
                    <h3>Pending Tickets</h3>
                </div>
            </div>
        </a>
    </div>
    <div class="col-xl-3 col-md-6">
        <a href="{% url 'tracker:open' %}" class="text-decoration-none">
            <div class="card bg-danger text-light text-center mb-4 p-3">
                <div class="card-body">
                    <h3>Open Tickets</h3>
                </div>
            </div>
        </a>
    </div>
</div>

tracker/templates/tracker/general/includes/charts.html
<div class="row">
    <div class="col-xl-6 mb-5">
        <div class="card">
            <div class="card-header">Line Chart Header</div>
            <div class="card-body"><canvas id="myChartline"></canvas></div>
        </div>
    </div>
    <div class="col-xl-6 mb-5">
        <div class="card">
            <div class="card-header">Pie Chart Header</div>
            <div class="card-body"><canvas id="myChartBar"></canvas></div>
        </div>
    </div>
</div>

tracker/templates/tracker/general/includes/top_tickets.html
<div class="card mb-5">
    <div class="card-header">Top 10 Voted Tickets</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Ticket</th>
                        <th scope="col">Created By</th>
                        <th scope="col">Type</th>
                        <th scope="col">Priority</th>
                        <th scope="col">Votes</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in tickets %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></td>
                            <td>{{ obj.creator.username }}</td>
                            <td>{{ obj.type }}</td>
                            <td>{{ obj.priority }}</td>
                            <td>{{ obj.votes }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>