bug_tracker/urls.py
# https://docs.djangoproject.com/en/3.2/topics/http/urls/

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('tracker/', include('tracker.urls')),
    path('', include('home.urls')),
    path('users/', include('users.urls')),

]

handler400 = 'home.views.error_400'
handler403 = 'home.views.error_403'
handler404 = 'home.views.error_404'
handler500 = 'home.views.error_500'

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
	path('', views.HomeView.as_view(), name='home')
]

tracker/urls.py
from django.urls import path
from tracker.views import tracker, ticket, ticket_comment, general


app_name = 'tracker'
urlpatterns = [
	# GENERAL
	path('dashboard/', general.Dashboard.as_view(), name='dashboard'),
	path('solved/', general.SolvedTicketListView.as_view(), name='solved'),
	path('closed/', general.ClosedTicketListView.as_view(), name='closed'),
	path('pending/', general.PendingTicketListView.as_view(), name='pending'),
	path('open/', general.OpenTicketListView.as_view(), name='open'),

	# TRACKER
	path('list/', tracker.TrackerListView.as_view(), name='tracker-list'),
	path('create/', tracker.TrackerCreateView.as_view(), name='tracker-create'),
	path('<int:pk>/', tracker.TrackerDetailView.as_view(), name='tracker-detail'),
	path('update/<int:pk>/', tracker.TrackerUpdateView.as_view(), name='tracker-update'),
	path('delete/<int:pk>/', tracker.TrackerDeleteView.as_view(), name='tracker-delete'),

	# TICKET
	path('<int:tracker_pk>/ticket/create/', ticket.TicketCreateView.as_view(), name='ticket-create'),
	path('<int:tracker_pk>/ticket/<int:pk>/', ticket.TicketDetailView.as_view(), name='ticket-detail'),
	path('<int:tracker_pk>/ticket/update/<int:pk>/', ticket.TicketUpdateView.as_view(), name='ticket-update'),
	path('<int:tracker_pk>/ticket/delete/<int:pk>/', ticket.TicketDeleteView.as_view(), name='ticket-delete'),

	# TICKET COMMENT
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/create/', ticket_comment.TicketCommentCreateView.as_view(), name='ticket-comment-create'),
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/update/<int:pk>/', ticket_comment.TicketCommentUpdateView.as_view(), name='ticket-comment-update'),
	path('<int:tracker_pk>/ticket/<int:ticket_pk>/ticket-comment/delete/<int:pk>/', ticket_comment.TicketCommentDeleteView.as_view(), name='ticket-comment-delete'),

]

templates/components/navbar.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/components_styles/navbar.css' %}">
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">

        <a class="navbar-brand" href="/">Project</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tracker:dashboard' %}">Dashboard</a>
                    </li>
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li class="nav-item" id="logout-nav-item">
                        <a class="nav-link" id="logout-nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item" id="login-nav-item">
                        <a class="nav-link" id="login-nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item" id="signup-nav-item">
                        <a class="nav-link" id="signup-nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


templates/components/nothing.html
<h1 class="text-center">There is nothing to display.</h1>

templates/components/paginator.html
{% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
        {% endif %}

        {% if page_obj.number|add:'-4' > 1 %}
            <li class="page-item">
                {# Question: &hellip; instead of ... #}
                <a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">...</a>
            </li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">
                        {{ i }}
                        <span class="sr-only"></span>
                    </span>
                </li>
            {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                 <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">...</a></li>
        {% endif %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
        {% endif %}
    </ul>
{% endif %}